import type { Metadata } from "next";
import "./globals.css";
import { PlayfairDisplay } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Color Palette finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${PlayfairDisplay.className} antialiased`}>
        <div className="opacity-100 ">{children}</div>
      </body>
    </html>
  );
}
